### ISSUE TITLE
hello 你好，我正常写不生效。

### ISSUE THREAD

**Issue by xiaoxiaohuayu** [Mitscherlich/vue-use-hotkeys#479]
希望作者有空能看一下下。
vue：3.4.2
macOS：14.5 (23F79)
Microsoft Edge 版本 130.0.2849.80 (正式版本) (x86_64)
bad：
```  
useHotkeys('a', ()=>{
    console.log('a');
})
```

使用hotkeys-js 可以

good
```  
hotkeys('b', (event, handler)=>{
    console.log('you pressed b!')
  });
```

**Comment by Mitscherlich** [comment]
你好，请提供下可复现的demo

**Comment by xiaoxiaohuayu** [comment]
> 你好，请提供下可复现的demo

https://github.com/Mitscherlich/vue-use-hotkeys/issues/479#issuecomment-2469966908   
大佬顺便问下 hotkeys-js 是不支持 code去调用的吗？
像这样
`
hotkeys('16', (event, handler)=>{});
`

**Comment by Mitscherlich** [comment]
![image](https://github.com/user-attachments/assets/e743aac4-e1b3-442f-b132-2d06c2e0978e)

看上去是正常的，你的原 demo 中未引入使用了 `vue-use-hotkeys` 的组件，将 `App.vue` 改为以下内容后可以正常使用：

```diff
<template>
-  <h1>Hello vue-use-hotkeys</h1>
+  <WelcomeItem />
</template>

<script setup lang="ts">
- import { ref } from "vue";
+ import WelcomeItem from './components/WelcomeItem.vue';
- const msg = ref<string>("World");
</script>

```

**Comment by Mitscherlich** [comment]
使用 edge 也可以正常触发：

![image](https://github.com/user-attachments/assets/0a85e787-fee1-4156-a160-9cd1109e869d)

**Comment by xiaoxiaohuayu** [comment]
我.....白痴了. 是正常的
